export interface Kosakata {
  kata: string
  arti: string
  romaji: string
  kategori: 'kata-benda' | 'kata-kerja' | 'kata-sifat' | 'kata-keterangan' | 'partikel' | 'ungkapan'
  contoh?: string
  contohArti?: string
}

export const kosakataN5Data: Kosakata[] = [
  // Kata Benda (名詞)
  { kata: "学生", arti: "siswa/mahasiswa", romaji: "gakusei", kategori: "kata-benda" },
  { kata: "先生", arti: "guru", romaji: "sensei", kategori: "kata-benda" },
  { kata: "会社", arti: "perusahaan", romaji: "kaisha", kategori: "kata-benda" },
  { kata: "仕事", arti: "pekerjaan", romaji: "shigoto", kategori: "kata-benda" },
  { kata: "学校", arti: "sekolah", romaji: "gakkou", kategori: "kata-benda" },
  { kata: "大学", arti: "universitas", romaji: "daigaku", kategori: "kata-benda" },
  { kata: "時間", arti: "waktu", romaji: "jikan", kategori: "kata-benda" },
  { kata: "昨日", arti: "kemarin", romaji: "kinou", kategori: "kata-benda" },
  { kata: "今日", arti: "hari ini", romaji: "kyou", kategori: "kata-benda" },
  { kata: "明日", arti: "besok", romaji: "ashita", kategori: "kata-benda" },
  { kata: "年", arti: "tahun", romaji: "nen", kategori: "kata-benda" },
  { kata: "月", arti: "bulan", romaji: "gatsu", kategori: "kata-benda" },
  { kata: "日", arti: "hari", romaji: "nichi", kategori: "kata-benda" },
  { kata: "時", arti: "jam (waktu)", romaji: "ji", kategori: "kata-benda" },
  { kata: "分", arti: "menit", romaji: "fun", kategori: "kata-benda" },
  { kata: "名前", arti: "nama", romaji: "namae", kategori: "kata-benda" },
  { kata: "人", arti: "orang", romaji: "hito", kategori: "kata-benda" },
  { kata: "友達", arti: "teman", romaji: "tomodachi", kategori: "kata-benda" },
  { kata: "家族", arti: "keluarga", romaji: "kazoku", kategori: "kata-benda" },
  { kata: "父", arti: "ayah", romaji: "chichi", kategori: "kata-benda" },
  { kata: "母", arti: "ibu", romaji: "haha", kategori: "kata-benda" },
  { kata: "子供", arti: "anak-anak", romaji: "kodomo", kategori: "kata-benda" },
  { kata: "男", arti: "laki-laki", romaji: "otoko", kategori: "kata-benda" },
  { kata: "女", arti: "perempuan", romaji: "onna", kategori: "kata-benda" },
  { kata: "目", arti: "mata", romaji: "me", kategori: "kata-benda" },
  { kata: "耳", arti: "telinga", romaji: "mimi", kategori: "kata-benda" },
  { kata: "口", arti: "mulut", romaji: "kuchi", kategori: "kata-benda" },
  { kata: "手", arti: "tangan", romaji: "te", kategori: "kata-benda" },
  { kata: "足", arti: "kaki", romaji: "ashi", kategori: "kata-benda" },
  { kata: "山", arti: "gunung", romaji: "yama", kategori: "kata-benda" },
  { kata: "川", arti: "sungai", romaji: "kawa", kategori: "kata-benda" },
  { kata: "海", arti: "laut", romaji: "umi", kategori: "kata-benda" },
  { kata: "空", arti: "langit", romaji: "sora", kategori: "kata-benda" },
  { kata: "雨", arti: "hujan", romaji: "ame", kategori: "kata-benda" },
  { kata: "雪", arti: "salju", romaji: "yuki", kategori: "kata-benda" },
  { kata: "風", arti: "angin", romaji: "kaze", kategori: "kata-benda" },
  { kata: "花", arti: "bunga", romaji: "hana", kategori: "kata-benda" },
  { kata: "木", arti: "pohon", romaji: "ki", kategori: "kata-benda" },
  { kata: "林", arti: "hutan", romaji: "hayashi", kategori: "kata-benda" },
  { kata: "森", arti: "hutan lebat", romaji: "mori", kategori: "kata-benda" },
  { kata: "田", arti: "sawah", romaji: "ta", kategori: "kata-benda" },
  { kata: "道", arti: "jalan", romaji: "michi", kategori: "kata-benda" },
  { kata: "駅", arti: "stasiun", romaji: "eki", kategori: "kata-benda" },
  { kata: "車", arti: "mobil", romaji: "kuruma", kategori: "kata-benda" },
  { kata: "電車", arti: "kereta listrik", romaji: "densha", kategori: "kata-benda" },
  { kata: "自転車", arti: "sepeda", romaji: "jitensha", kategori: "kata-benda" },
  { kata: "飛行機", arti: "pesawat terbang", romaji: "hikouki", kategori: "kata-benda" },
  { kata: "船", arti: "kapal", romaji: "fune", kategori: "kata-benda" },
  { kata: "店", arti: "toko", romaji: "mise", kategori: "kata-benda" },
  { kata: "銀行", arti: "bank", romaji: "ginkou", kategori: "kata-benda" },
  { kata: "郵便局", arti: "kantor pos", romaji: "yuubinkyoku", kategori: "kata-benda" },
  { kata: "病院", arti: "rumah sakit", romaji: "byouin", kategori: "kata-benda" },
  { kata: "薬局", arti: "apotek", romaji: "yakkyoku", kategori: "kata-benda" },
  { kata: "図書館", arti: "perpustakaan", romaji: "toshokan", kategori: "kata-benda" },
  { kata: "公園", arti: "taman", romaji: "kouen", kategori: "kata-benda" },
  { kata: "動物園", arti: "kebun binatang", romaji: "doubutsuen", kategori: "kata-benda" },
  { kata: "映画館", arti: "bioskop", romaji: "eigakan", kategori: "kata-benda" },
  { kata: "美術館", arti: "museum seni", romaji: "bijutsukan", kategori: "kata-benda" },
  { kata: "店員", arti: "pegawai toko", romaji: "ten-in", kategori: "kata-benda" },
  { kata: "社員", arti: "karyawan perusahaan", romaji: "shain", kategori: "kata-benda" },
  { kata: "医者", arti: "dokter", romaji: "isha", kategori: "kata-benda" },
  { kata: "看護師", arti: "perawat", romaji: "kangoshi", kategori: "kata-benda" },
  { kata: "警察", arti: "polisi", romaji: "keisatsu", kategori: "kata-benda" },
  { kata: "消防士", arti: "pemadam kebakaran", romaji: "shouboushi", kategori: "kata-benda" },
  { kata: "運転手", arti: "sopir", romaji: "untenshu", kategori: "kata-benda" },
  { kata: "料理人", arti: "koki", romaji: "ryourinin", kategori: "kata-benda" },
  { kata: "歌手", arti: "penyanyi", romaji: "kashu", kategori: "kata-benda" },
  { kata: "作家", arti: "penulis", romaji: "sakka", kategori: "kata-benda" },
  { kata: "画家", arti: "pelukis", romaji: "gaka", kategori: "kata-benda" },
  { kata: "音楽家", arti: "musisi", romaji: "ongakuka", kategori: "kata-benda" },
  { kata: "映画監督", arti: "sutradara film", romaji: "eiga kantoku", kategori: "kata-benda" },
  { kata: "建築家", arti: "arsitek", romaji: "kenchikuka", kategori: "kata-benda" },
  { kata: "弁護士", arti: "pengacara", romaji: "bengoshi", kategori: "kata-benda" },
  { kata: "会計士", arti: "akuntan", romaji: "kaikeishi", kategori: "kata-benda" },
  { kata: "教師", arti: "pengajar", romaji: "kyoushi", kategori: "kata-benda" },
  { kata: "研究者", arti: "peneliti", romaji: "kenkyuusha", kategori: "kata-benda" },
  { kata: "科学者", arti: "ilmuwan", romaji: "kagakusha", kategori: "kata-benda" },
  { kata: "技術者", arti: "teknisi", romaji: "gijutsusha", kategori: "kata-benda" },
  { kata: "プログラマー", arti: "programmer", romaji: "purogurama", kategori: "kata-benda" },
  { kata: "デザイナー", arti: "desainer", romaji: "dezanai", kategori: "kata-benda" },
  { kata: "エンジニア", arti: "insinyur", romaji: "enjinia", kategori: "kata-benda" },
  { kata: "社長", arti: "direktur", romaji: "shachou", kategori: "kata-benda" },
  { kata: "部長", arti: "kepala bagian", romaji: "buchou", kategori: "kata-benda" },
  { kata: "課長", arti: "kepala seksi", romaji: "kachou", kategori: "kata-benda" },
  { kata: "係長", arti: "kepala unit", romaji: "kakarichou", kategori: "kata-benda" },
  { kata: "社員", arti: "staf", romaji: "shain", kategori: "kata-benda" },
  { kata: "事務員", arti: "petugas administrasi", romaji: "jimuin", kategori: "kata-benda" },

  // Kata Kerja (動詞)
  { kata: "行く", arti: "pergi", romaji: "iku", kategori: "kata-kerja" },
  { kata: "来る", arti: "datang", romaji: "kuru", kategori: "kata-kerja" },
  { kata: "帰る", arti: "pulang", romaji: "kaeru", kategori: "kata-kerja" },
  { kata: "食べる", arti: "makan", romaji: "taberu", kategori: "kata-kerja" },
  { kata: "飲む", arti: "minum", romaji: "nomu", kategori: "kata-kerja" },
  { kata: "見る", arti: "melihat", romaji: "miru", kategori: "kata-kerja" },
  { kata: "聞く", arti: "mendengar", romaji: "kiku", kategori: "kata-kerja" },
  { kata: "話す", arti: "berbicara", romaji: "hanasu", kategori: "kata-kerja" },
  { kata: "読む", arti: "membaca", romaji: "yomu", kategori: "kata-kerja" },
  { kata: "書く", arti: "menulis", romaji: "kaku", kategori: "kata-kerja" },
  { kata: "買う", arti: "membeli", romaji: "kau", kategori: "kata-kerja" },
  { kata: "売る", arti: "menjual", romaji: "uru", kategori: "kata-kerja" },
  { kata: "作る", arti: "membuat", romaji: "tsukuru", kategori: "kata-kerja" },
  { kata: "使う", arti: "menggunakan", romaji: "tsukau", kategori: "kata-kerja" },
  { kata: "知る", arti: "mengetahui", romaji: "shiru", kategori: "kata-kerja" },
  { kata: "思う", arti: "berpikir", romaji: "omou", kategori: "kata-kerja" },
  { kata: "考える", arti: "mempertimbangkan", romaji: "kangaeru", kategori: "kata-kerja" },
  { kata: "見つける", arti: "menemukan", romaji: "mitsukeru", kategori: "kata-kerja" },
  { kata: "待つ", arti: "menunggu", romaji: "matsu", kategori: "kata-kerja" },
  { kata: "会う", arti: "bertemu", romaji: "au", kategori: "kata-kerja" },
  { kata: "教える", arti: "mengajar", romaji: "oshieru", kategori: "kata-kerja" },
  { kata: "習う", arti: "belajar", romaji: "narau", kategori: "kata-kerja" },
  { kata: "勉強する", arti: "belajar (aktivitas)", romaji: "benkyou suru", kategori: "kata-kerja" },
  { kata: "働く", arti: "bekerja", romaji: "hataraku", kategori: "kata-kerja" },
  { kata: "休む", arti: "istirahat", romaji: "yasumu", kategori: "kata-kerja" },
  { kata: "寝る", arti: "tidur", romaji: "neru", kategori: "kata-kerja" },
  { kata: "起きる", arti: "bangun", romaji: "okiru", kategori: "kata-kerja" },
  { kata: "入る", arti: "masuk", romaji: "hairu", kategori: "kata-kerja" },
  { kata: "出る", arti: "keluar", romaji: "deru", kategori: "kata-kerja" },
  { kata: "開ける", arti: "membuka", romaji: "akeru", kategori: "kata-kerja" },
  { kata: "閉める", arti: "menutup", romaji: "shimeru", kategori: "kata-kerja" },
  { kata: "始める", arti: "memulai", romaji: "hajimeru", kategori: "kata-kerja" },
  { kata: "終わる", arti: "selesai", romaji: "owaru", kategori: "kata-kerja" },
  { kata: "持つ", arti: "memegang/memiliki", romaji: "motsu", kategori: "kata-kerja" },
  { kata: "取る", arti: "mengambil", romaji: "toru", kategori: "kata-kerja" },
  { kata: "置く", arti: "meletakkan", romaji: "oku", kategori: "kata-kerja" },
  { kata: "作る", arti: "membuat", romaji: "tsukuru", kategori: "kata-kerja" },
  { kata: "壊す", arti: "merusak", romaji: "kowasu", kategori: "kata-kerja" },
  { kata: "直す", arti: "memperbaiki", romaji: "naosu", kategori: "kata-kerja" },
  { kata: "洗う", arti: "mencuci", romaji: "arau", kategori: "kata-kerja" },
  { kata: "掃除する", arti: "membersihkan", romaji: "souji suru", kategori: "kata-kerja" },
  { kata: "料理する", arti: "memasak", romaji: "ryouri suru", kategori: "kata-kerja" },
  { kata: "運転する", arti: "mengemudi", romaji: "unten suru", kategori: "kata-kerja" },
  { kata: "歩く", arti: "berjalan", romaji: "aruku", kategori: "kata-kerja" },
  { kata: "走る", arti: "berlari", romaji: "hashiru", kategori: "kata-kerja" },
  { kata: "泳ぐ", arti: "berenang", romaji: "oyogu", kategori: "kata-kerja" },
  { kata: "飛ぶ", arti: "terbang", romaji: "tobu", kategori: "kata-kerja" },
  { kata: "遊ぶ", arti: "bermain", romaji: "asobu", kategori: "kata-kerja" },
  { kata: "歌う", arti: "menyanyi", romaji: "utau", kategori: "kata-kerja" },
  { kata: "踊る", arti: "menari", romaji: "odoru", kategori: "kata-kerja" },
  { kata: "笑う", arti: "tertawa", romaji: "warau", kategori: "kata-kerja" },
  { kata: "泣く", arti: "menangis", romaji: "naku", kategori: "kata-kerja" },
  { kata: "怒る", arti: "marah", romaji: "okoru", kategori: "kata-kerja" },
  { kata: "喜ぶ", arti: "bersuka cita", romaji: "yorokobu", kategori: "kata-kerja" },
  { kata: "悲しむ", arti: "bersedih", romaji: "kanashimu", kategori: "kata-kerja" },
  { kata: "驚く", arti: "terkejut", romaji: "odoroku", kategori: "kata-kerja" },
  { kata: "怖がる", arti: "takut", romaji: "kowagaru", kategori: "kata-kerja" },
  { kata: "恥ずかしがる", arti: "malu", romaji: "hazukashigaru", kategori: "kata-kerja" },
  { kata: "頑張る", arti: "berusaha keras", romaji: "ganbaru", kategori: "kata-kerja" },

  // Kata Sifat (形容詞)
  { kata: "大きい", arti: "besar", romaji: "ookii", kategori: "kata-sifat" },
  { kata: "小さい", arti: "kecil", romaji: "chiisai", kategori: "kata-sifat" },
  { kata: "高い", arti: "tinggi/mahal", romaji: "takai", kategori: "kata-sifat" },
  { kata: "安い", arti: "murah", romaji: "yasui", kategori: "kata-sifat" },
  { kata: "新しい", arti: "baru", romaji: "atarashii", kategori: "kata-sifat" },
  { kata: "古い", arti: "lama", romaji: "furui", kategori: "kata-sifat" },
  { kata: "良い", arti: "baik", romaji: "yoi/ii", kategori: "kata-sifat" },
  { kata: "悪い", arti: "buruk", romaji: "warui", kategori: "kata-sifat" },
  { kata: "多い", arti: "banyak", romaji: "ooi", kategori: "kata-sifat" },
  { kata: "少ない", arti: "sedikit", romaji: "sukunai", kategori: "kata-sifat" },
  { kata: "長い", arti: "panjang", romaji: "nagai", kategori: "kata-sifat" },
  { kata: "短い", arti: "pendek", romaji: "mijikai", kategori: "kata-sifat" },
  { kata: "広い", arti: "luas", romaji: "hiroi", kategori: "kata-sifat" },
  { kata: "狭い", arti: "sempit", romaji: "semai", kategori: "kata-sifat" },
  { kata: "暑い", arti: "panas (cuaca)", romaji: "atsui", kategori: "kata-sifat" },
  { kata: "寒い", arti: "dingin (cuaca)", romaji: "samui", kategori: "kata-sifat" },
  { kata: "熱い", arti: "panas (benda)", romaji: "atsui", kategori: "kata-sifat" },
  { kata: "冷たい", arti: "dingin (benda)", romaji: "tsumetai", kategori: "kata-sifat" },
  { kata: "暖かい", arti: "hangat", romaji: "atatakai", kategori: "kata-sifat" },
  { kata: "涼しい", arti: "sejuk", romaji: "suzushii", kategori: "kata-sifat" },
  { kata: "明るい", arti: "terang", romaji: "akarui", kategori: "kata-sifat" },
  { kata: "暗い", arti: "gelap", romaji: "kurai", kategori: "kata-sifat" },
  { kata: "重い", arti: "berat", romaji: "omoi", kategori: "kata-sifat" },
  { kata: "軽い", arti: "ringan", romaji: "karui", kategori: "kata-sifat" },
  { kata: "難しい", arti: "sulit", romaji: "muzukashii", kategori: "kata-sifat" },
  { kata: "易しい", arti: "mudah", romaji: "yasashii", kategori: "kata-sifat" },
  { kata: "忙しい", arti: "sibuk", romaji: "isogashii", kategori: "kata-sifat" },
  { kata: "暇", arti: "senggang", romaji: "hima", kategori: "kata-sifat" },
  { kata: "楽しい", arti: "menyenangkan", romaji: "tanoshii", kategori: "kata-sifat" },
  { kata: "面白い", arti: "menarik", romaji: "omoshiroi", kategori: "kata-sifat" },
  { kata: "つまらない", arti: "membosankan", romaji: "tsumaranai", kategori: "kata-sifat" },
  { kata: "怖い", arti: "menakutkan", romaji: "kowai", kategori: "kata-sifat" },
  { kata: "痛い", arti: "sakit", romaji: "itai", kategori: "kata-sifat" },
  { kata: "痒い", arti: "gatal", romaji: "kayui", kategori: "kata-sifat" },
  { kata: "美味しい", arti: "enak", romaji: "oishii", kategori: "kata-sifat" },
  { kata: "不味い", arti: "tidak enak", romaji: "mazui", kategori: "kata-sifat" },
  { kata: "甘い", arti: "manis", romaji: "amai", kategori: "kata-sifat" },
  { kata: "辛い", arti: "pedas", romaji: "karai", kategori: "kata-sifat" },
  { kata: "塩辛い", arti: "asin", romaji: "shiokarai", kategori: "kata-sifat" },
  { kata: "苦い", arti: "pahit", romaji: "nigai", kategori: "kata-sifat" },
  { kata: "酸っぱい", arti: "asam", romaji: "suppai", kategori: "kata-sifat" },
  { kata: "渋い", arti: "sepet", romaji: "shibui", kategori: "kata-sifat" },
  { kata: "うまい", arti: "lezat", romaji: "umai", kategori: "kata-sifat" },
  { kata: "まずい", arti: "tidak lezat", romaji: "mazui", kategori: "kata-sifat" },
  { kata: "優しい", arti: "baik hati", romaji: "yasashii", kategori: "kata-sifat" },
  { kata: "親切", arti: "ramah", romaji: "shinsetsu", kategori: "kata-sifat" },
  { kata: "厳しい", arti: "ketat", romaji: "kibishii", kategori: "kata-sifat" },
  { kata: "優しい", arti: "lembut", romaji: "yasashii", kategori: "kata-sifat" },
  { kata: "冷たい", arti: "dingin (sikap)", romaji: "tsumetai", kategori: "kata-sifat" },
  { kata: "暖かい", arti: "hangat (sikap)", romaji: "atatakai", kategori: "kata-sifat" },
  { kata: "真面目", arti: "serius", romaji: "majime", kategori: "kata-sifat" },
  { kata: "不真面目", arti: "tidak serius", romaji: "fumajime", kategori: "kata-sifat" },
  { kata: "真剣", arti: "sungguh-sungguh", romaji: "shinken", kategori: "kata-sifat" },
  { kata: "真っ直ぐ", arti: "lurus", romaji: "massugu", kategori: "kata-sifat" },
  { kata: "曲がった", arti: "bengkok", romaji: "magatta", kategori: "kata-sifat" },
  { kata: "丸い", arti: "bulat", romaji: "marui", kategori: "kata-sifat" },
  { kata: "四角い", arti: "persegi", romaji: "shikakui", kategori: "kata-sifat" },
  { kata: "三角", arti: "segitiga", romaji: "sankaku", kategori: "kata-sifat" },
  { kata: "同じ", arti: "sama", romaji: "onaji", kategori: "kata-sifat" },
  { kata: "違う", arti: "berbeda", romaji: "chigau", kategori: "kata-sifat" },
  { kata: "特別", arti: "khusus", romaji: "tokubetsu", kategori: "kata-sifat" },
  { kata: "普通", arti: "biasa", romaji: "futsuu", kategori: "kata-sifat" },
  { kata: "特別", arti: "istimewa", romaji: "tokubetsu", kategori: "kata-sifat" },
  { kata: "異常", arti: "tidak normal", romaji: "ijou", kategori: "kata-sifat" },
  { kata: "正常", arti: "normal", romaji: "seijou", kategori: "kata-sifat" },
  { kata: "変", arti: "aneh", romaji: "hen", kategori: "kata-sifat" },
  { kata: "奇妙", arti: "aneh (lebih formal)", romaji: "kimyou", kategori: "kata-sifat" },
  { kata: "不思議", arti: "ajaib", romaji: "fushigi", kategori: "kata-sifat" },
  { kata: "神秘", arti: "misterius", romaji: "shinpi", kategori: "kata-sifat" },

  // Kata Keterangan (副詞)
  { kata: "よく", arti: "sering/baik", romaji: "yoku", kategori: "kata-keterangan" },
  { kata: "ときどき", arti: "kadang-kadang", romaji: "tokidoki", kategori: "kata-keterangan" },
  { kata: "あまり", arti: "tidak terlalu", romaji: "amari", kategori: "kata-keterangan" },
  { kata: "全然", arti: "sama sekali (tidak)", romaji: "zenzen", kategori: "kata-keterangan" },
  { kata: "少し", arti: "sedikit", romaji: "sukoshi", kategori: "kata-keterangan" },
  { kata: "たくさん", arti: "banyak", romaji: "takusan", kategori: "kata-keterangan" },
  { kata: "とても", arti: "sangat", romaji: "totemo", kategori: "kata-keterangan" },
  { kata: "あまり", arti: "tidak begitu", romaji: "amari", kategori: "kata-keterangan" },
  { kata: "すぐに", arti: "segera", romaji: "sugu ni", kategori: "kata-keterangan" },
  { kata: "もう", arti: "sudah", romaji: "mou", kategori: "kata-keterangan" },
  { kata: "まだ", arti: "masih", romaji: "mada", kategori: "kata-keterangan" },
  { kata: "もう一度", arti: "sekali lagi", romaji: "mou ichido", kategori: "kata-keterangan" },
  { kata: "いつも", arti: "selalu", romaji: "itsumo", kategori: "kata-keterangan" },
  { kata: "だいたい", arti: "kira-kira", romaji: "daitai", kategori: "kata-keterangan" },
  { kata: "ちょうど", arti: "tepat", romaji: "choudo", kategori: "kata-keterangan" },
  { kata: "特に", arti: "terutama", romaji: "toku ni", kategori: "kata-keterangan" },
  { kata: "一緒に", arti: "bersama", romaji: "issho ni", kategori: "kata-keterangan" },
  { kata: "別々に", arti: "terpisah", romaji: "betsu betsu ni", kategori: "kata-keterangan" },
  { kata: "突然", arti: "tiba-tiba", romaji: "totsuzen", kategori: "kata-keterangan" },
  { kata: "急に", arti: "mendadak", romaji: "kyuu ni", kategori: "kata-keterangan" },
  { kata: "ゆっくり", arti: "perlahan", romaji: "yukkuri", kategori: "kata-keterangan" },
  { kata: "速く", arti: "cepat", romaji: "hayaku", kategori: "kata-keterangan" },
  { kata: "遅く", arti: "lambat", romaji: "osoku", kategori: "kata-keterangan" },
  { kata: "静かに", arti: "dengan tenang", romaji: "shizuka ni", kategori: "kata-keterangan" },
  { kata: "うるさく", arti: "dengan berisik", romaji: "urusaku", kategori: "kata-keterangan" },
  { kata: "明るく", arti: "dengan terang", romaji: "akaruku", kategori: "kata-keterangan" },
  { kata: "暗く", arti: "dengan gelap", romaji: "kuraku", kategori: "kata-keterangan" },
  { kata: "大きく", arti: "dengan besar", romaji: "ookiku", kategori: "kata-keterangan" },
  { kata: "小さく", arti: "dengan kecil", romaji: "chiisaku", kategori: "kata-keterangan" },
  { kata: "高く", arti: "dengan tinggi", romaji: "takaku", kategori: "kata-keterangan" },
  { kata: "安く", arti: "dengan murah", romaji: "yasuku", kategori: "kata-keterangan" },
  { kata: "新しく", arti: "dengan baru", romaji: "atarashiku", kategori: "kata-keterangan" },
  { kata: "古く", arti: "dengan lama", romaji: "furuku", kategori: "kata-keterangan" },
  { kata: "良く", arti: "dengan baik", romaji: "yoku", kategori: "kata-keterangan" },
  { kata: "悪く", arti: "dengan buruk", romaji: "waruku", kategori: "kata-keterangan" },
  { kata: "多く", arti: "dengan banyak", romaji: "ooku", kategori: "kata-keterangan" },
  { kata: "少なく", arti: "dengan sedikit", romaji: "sukunaku", kategori: "kata-keterangan" },
  { kata: "長く", arti: "dengan panjang", romaji: "nagaku", kategori: "kata-keterangan" },
  { kata: "短く", arti: "dengan pendek", romaji: "mijikaku", kategori: "kata-keterangan" },
  { kata: "広く", arti: "dengan luas", romaji: "hiroku", kategori: "kata-keterangan" },
  { kata: "狭く", arti: "dengan sempit", romaji: "semaku", kategori: "kata-keterangan" },
  { kata: "暑く", arti: "dengan panas", romaji: "atsuku", kategori: "kata-keterangan" },
  { kata: "寒く", arti: "dengan dingin", romaji: "samuku", kategori: "kata-keterangan" },
  { kata: "熱く", arti: "dengan panas (benda)", romaji: "atsuku", kategori: "kata-keterangan" },
  { kata: "冷たく", arti: "dengan dingin (benda)", romaji: "tsumetaku", kategori: "kata-keterangan" },
  { kata: "暖かく", arti: "dengan hangat", romaji: "atatakaku", kategori: "kata-keterangan" },
  { kata: "涼しく", arti: "dengan sejuk", romaji: "suzushiku", kategori: "kata-keterangan" },
  { kata: "明るく", arti: "dengan terang", romaji: "akaruku", kategori: "kata-keterangan" },
  { kata: "暗く", arti: "dengan gelap", romaji: "kuraku", kategori: "kata-keterangan" },
  { kata: "重く", arti: "dengan berat", romaji: "omoku", kategori: "kata-keterangan" },
  { kata: "軽く", arti: "dengan ringan", romaji: "karuku", kategori: "kata-keterangan" },
  { kata: "難しく", arti: "dengan sulit", romaji: "muzukashiku", kategori: "kata-keterangan" },
  { kata: "易しく", arti: "dengan mudah", romaji: "yasashiku", kategori: "kata-keterangan" },
  { kata: "忙しく", arti: "dengan sibuk", romaji: "isogashiku", kategori: "kata-keterangan" },
  { kata: "暇に", arti: "dengan senggang", romaji: "hima ni", kategori: "kata-keterangan" },
  { kata: "楽しく", arti: "dengan menyenangkan", romaji: "tanoshiku", kategori: "kata-keterangan" },
  { kata: "面白く", arti: "dengan menarik", romaji: "omoshiroku", kategori: "kata-keterangan" },
  { kata: "つまらなく", arti: "dengan membosankan", romaji: "tsumaranaku", kategori: "kata-keterangan" },
  { kata: "怖く", arti: "dengan menakutkan", romaji: "kowaku", kategori: "kata-keterangan" },
  { kata: "痛く", arti: "dengan sakit", romaji: "itaku", kategori: "kata-keterangan" },
  { kata: "痒く", arti: "dengan gatal", romaji: "kayuku", kategori: "kata-keterangan" },
  { kata: "美味しく", arti: "dengan enak", romaji: "oishiku", kategori: "kata-keterangan" },
  { kata: "不味く", arti: "dengan tidak enak", romaji: "mazuku", kategori: "kata-keterangan" },
  { kata: "甘く", arti: "dengan manis", romaji: "amaku", kategori: "kata-keterangan" },
  { kata: "辛く", arti: "dengan pedas", romaji: "karaku", kategori: "kata-keterangan" },
  { kata: "塩辛く", arti: "dengan asin", romaji: "shiokaraku", kategori: "kata-keterangan" },
  { kata: "苦く", arti: "dengan pahit", romaji: "nigaku", kategori: "kata-keterangan" },
  { kata: "酸っぱく", arti: "dengan asam", romaji: "suppaku", kategori: "kata-keterangan" },
  { kata: "渋く", arti: "dengan sepet", romaji: "shibuku", kategori: "kata-keterangan" },
  { kata: "うまく", arti: "dengan lezat", romaji: "umaku", kategori: "kata-keterangan" },
  { kata: "まずく", arti: "dengan tidak lezat", romaji: "mazuku", kategori: "kata-keterangan" },
  { kata: "優しく", arti: "dengan baik hati", romaji: "yasashiku", kategori: "kata-keterangan" },
  { kata: "親切に", arti: "dengan ramah", romaji: "shinsetsu ni", kategori: "kata-keterangan" },
  { kata: "厳しく", arti: "dengan ketat", romaji: "kibishiku", kategori: "kata-keterangan" },
  { kata: "優しく", arti: "dengan lembut", romaji: "yasashiku", kategori: "kata-keterangan" },
  { kata: "冷たく", arti: "dengan dingin (sikap)", romaji: "tsumetaku", kategori: "kata-keterangan" },
  { kata: "暖かく", arti: "dengan hangat (sikap)", romaji: "atatakaku", kategori: "kata-keterangan" },
  { kata: "真面目に", arti: "dengan serius", romaji: "majime ni", kategori: "kata-keterangan" },
  { kata: "不真面目に", arti: "dengan tidak serius", romaji: "fumajime ni", kategori: "kata-keterangan" },
  { kata: "真剣に", arti: "dengan sungguh-sungguh", romaji: "shinken ni", kategori: "kata-keterangan" },
  { kata: "真っ直ぐに", arti: "dengan lurus", romaji: "massugu ni", kategori: "kata-keterangan" },
  { kata: "曲がって", arti: "dengan bengkok", romaji: "magatte", kategori: "kata-keterangan" },
  { kata: "丸く", arti: "dengan bulat", romaji: "maruku", kategori: "kata-keterangan" },
  { kata: "四角く", arti: "dengan persegi", romaji: "shikakuku", kategori: "kata-keterangan" },
  { kata: "三角に", arti: "dengan segitiga", romaji: "sankaku ni", kategori: "kata-keterangan" },
  { kata: "同じに", arti: "dengan sama", romaji: "onaji ni", kategori: "kata-keterangan" },
  { kata: "違って", arti: "dengan berbeda", romaji: "chigatte", kategori: "kata-keterangan" },
  { kata: "特別に", arti: "dengan khusus", romaji: "tokubetsu ni", kategori: "kata-keterangan" },
  { kata: "普通に", arti: "dengan biasa", romaji: "futsuu ni", kategori: "kata-keterangan" },
  { kata: "特別に", arti: "dengan istimewa", romaji: "tokubetsu ni", kategori: "kata-keterangan" },
  { kata: "異常に", arti: "dengan tidak normal", romaji: "ijou ni", kategori: "kata-keterangan" },
  { kata: "正常に", arti: "dengan normal", romaji: "seijou ni", kategori: "kata-keterangan" },
  { kata: "変に", arti: "dengan aneh", romaji: "hen ni", kategori: "kata-keterangan" },
  { kata: "奇妙に", arti: "dengan aneh (lebih formal)", romaji: "kimyou ni", kategori: "kata-keterangan" },
  { kata: "不思議に", arti: "dengan ajaib", romaji: "fushigi ni", kategori: "kata-keterangan" },
  { kata: "神秘的に", arti: "dengan misterius", romaji: "shinpiteki ni", kategori: "kata-keterangan" },

  // Partikel (助詞)
  { kata: "は", arti: "partikel topik", romaji: "wa", kategori: "partikel" },
  { kata: "が", arti: "partikel subjek", romaji: "ga", kategori: "partikel" },
  { kata: "を", arti: "partikel objek", romaji: "wo", kategori: "partikel" },
  { kata: "に", arti: "partikel arah/waktu", romaji: "ni", kategori: "partikel" },
  { kata: "で", arti: "partikel tempat/alat", romaji: "de", kategori: "partikel" },
  { kata: "と", arti: "partikel dan/dengan", romaji: "to", kategori: "partikel" },
  { kata: "も", arti: "partikel juga", romaji: "mo", kategori: "partikel" },
  { kata: "から", arti: "partikel dari", romaji: "kara", kategori: "partikel" },
  { kata: "まで", arti: "partikel sampai", romaji: "made", kategori: "partikel" },
  { kata: "へ", arti: "partikel ke (arah)", romaji: "he", kategori: "partikel" },
  { kata: "や", arti: "partikel dan (sebagian)", romaji: "ya", kategori: "partikel" },
  { kata: "など", arti: "partikel dll", romaji: "nado", kategori: "partikel" },
  { kata: "か", arti: "partikel pertanyaan", romaji: "ka", kategori: "partikel" },
  { kata: "ね", arti: "partikel penegasan", romaji: "ne", kategori: "partikel" },
  { kata: "よ", arti: "partikel penekanan", romaji: "yo", kategori: "partikel" },
  { kata: "な", arti: "partikel larangan", romaji: "na", kategori: "partikel" },
  { kata: "なあ", arti: "partikel harapan", romaji: "naa", kategori: "partikel" },
  { kata: "さ", arti: "partikel informal", romaji: "sa", kategori: "partikel" },
  { kata: "ぜ", arti: "partikel ajakan (maskulin)", romaji: "ze", kategori: "partikel" },
  { kata: "ぞ", arti: "partikel penekanan (maskulin)", romaji: "zo", kategori: "partikel" },
  { kata: "わ", arti: "partikel feminin", romaji: "wa", kategori: "partikel" },
  { kata: "かしら", arti: "partikel keraguan (feminin)", romaji: "kashira", kategori: "partikel" },
  { kata: "って", arti: "partikel kutipan informal", romaji: "tte", kategori: "partikel" },
  { kata: "たら", arti: "partikel kondisi", romaji: "tara", kategori: "partikel" },
  { kata: "れば", arti: "partikel kondisi", romaji: "reba", kategori: "partikel" },
  { kata: "と", arti: "partikel kondisi", romaji: "to", kategori: "partikel" },
  { kata: "ば", arti: "partikel kondisi", romaji: "ba", kategori: "partikel" },
  { kata: "のに", arti: "partikel kontras", romaji: "noni", kategori: "partikel" },
  { kata: "ので", arti: "partikel alasan", romaji: "node", kategori: "partikel" },
  { kata: "から", arti: "partikel alasan", romaji: "kara", kategori: "partikel" },
  { kata: "て", arti: "partikel sambung", romaji: "te", kategori: "partikel" },
  { kata: "で", arti: "partikel sambung", romaji: "de", kategori: "partikel" },
  { kata: "し", arti: "partikel dan (penyebab)", romaji: "shi", kategori: "partikel" },
  { kata: "ながら", arti: "partikel sambil", romaji: "nagara", kategori: "partikel" },
  { kata: "たり", arti: "partikel contoh aktivitas", romaji: "tari", kategori: "partikel" },
  { kata: "とか", arti: "partikel contoh", romaji: "toka", kategori: "partikel" },
  { kata: "だの", arti: "partikel contoh (negatif)", romaji: "dano", kategori: "partikel" },
  { kata: "なり", arti: "partikel pilihan", romaji: "nari", kategori: "partikel" },
  { kata: "やら", arti: "partikel ketidakpastian", romaji: "yara", kategori: "partikel" },
  { kata: "こそ", arti: "partikel penekanan khusus", romaji: "koso", kategori: "partikel" },
  { kata: "さえ", arti: "partikel bahkan", romaji: "sae", kategori: "partikel" },
  { kata: "すら", arti: "partikel bahkan (formal)", romaji: "sura", kategori: "partikel" },
  { kata: "だけ", arti: "partikel hanya", romaji: "dake", kategori: "partikel" },
  { kata: "のみ", arti: "partikel hanya (formal)", romaji: "nomi", kategori: "partikel" },
  { kata: "ばかり", arti: "partikel hanya (negatif)", romaji: "bakari", kategori: "partikel" },
  { kata: "くらい", arti: "partikel kira-kira", romaji: "kurai", kategori: "partikel" },
  { kata: "ほど", arti: "partikel sejauh", romaji: "hodo", kategori: "partikel" },
  { kata: "など", arti: "partikel dan sebagainya", romaji: "nado", kategori: "partikel" },
  { kata: "なんて", arti: "partikel seperti", romaji: "nante", kategori: "partikel" },
  { kata: "なんか", arti: "partikel semacam", romaji: "nanka", kategori: "partikel" },
  { kata: "かどうか", arti: "partikel apakah atau tidak", romaji: "ka dou ka", kategori: "partikel" },
  { kata: "か何か", arti: "partikel atau sesuatu", romaji: "ka nanika", kategori: "partikel" },
  { kata: "かも知れない", arti: "partikel mungkin", romaji: "kamo shirenai", kategori: "partikel" },
  { kata: "かも", arti: "partikel mungkin (singkat)", romaji: "kamo", kategori: "partikel" },
  { kata: "か何か", arti: "partikel atau sesuatu", romaji: "ka nanika", kategori: "partikel" },
  { kata: "か何か", arti: "partikel atau sesuatu", romaji: "ka nanika", kategori: "partikel" },

  // Ungkapan (表現)
  { kata: "おはようございます", arti: "selamat pagi", romaji: "ohayou gozaimasu", kategori: "ungkapan" },
  { kata: "こんにちは", arti: "selamat siang", romaji: "konnichiwa", kategori: "ungkapan" },
  { kata: "こんばんは", arti: "selamat malam", romaji: "konbanwa", kategori: "ungkapan" },
  { kata: "おやすみなさい", arti: "selamat tidur", romaji: "oyasumi nasai", kategori: "ungkapan" },
  { kata: "ありがとうございます", arti: "terima kasih", romaji: "arigatou gozaimasu", kategori: "ungkapan" },
  { kata: "すみません", arti: "maaf/permisi", romaji: "sumimasen", kategori: "ungkapan" },
  { kata: "ごめんなさい", arti: "maaf", romaji: "gomen nasai", kategori: "ungkapan" },
  { kata: "お願いします", arti: "tolong", romaji: "onegaishimasu", kategori: "ungkapan" },
  { kata: "よろしくお願いします", arti: "senang berkenalan", romaji: "yoroshiku onegaishimasu", kategori: "ungkapan" },
  { kata: "いただきます", arti: "selamat makan", romaji: "itadakimasu", kategori: "ungkapan" },
  { kata: "ごちそうさまでした", arti: "terima kasih atas makanannya", romaji: "gochisousama deshita", kategori: "ungkapan" },
  { kata: "行ってきます", arti: "saya pergi dulu", romaji: "ittekimasu", kategori: "ungkapan" },
  { kata: "行ってらっしゃい", arti: "hati-hati di jalan", romaji: "itterasshai", kategori: "ungkapan" },
  { kata: "ただいま", arti: "saya pulang", romaji: "tadaima", kategori: "ungkapan" },
  { kata: "お帰りなさい", arti: "selamat datang kembali", romaji: "okaerinasai", kategori: "ungkapan" },
  { kata: "おめでとうございます", arti: "selamat", romaji: "omedetou gozaimasu", kategori: "ungkapan" },
  { kata: "お大事に", arti: "semoga lekas sembuh", romaji: "odaijini", kategori: "ungkapan" },
  { kata: "お疲れ様でした", arti: "terima kasih atas kerja kerasnya", romaji: "otsukaresama deshita", kategori: "ungkapan" },
  { kata: "失礼します", arti: "permisi", romaji: "shitsurei shimasu", kategori: "ungkapan" },
  { kata: "初めまして", arti: "senang berkenalan", romaji: "hajimemashite", kategori: "ungkapan" },
  { kata: "お久しぶりです", arti: "lama tidak berjumpa", romaji: "ohisashiburi desu", kategori: "ungkapan" },
  { kata: "元気ですか", arti: "apa kabar?", romaji: "genki desu ka", kategori: "ungkapan" },
  { kata: "お元気ですか", arti: "apa kabar? (formal)", romaji: "ogenki desu ka", kategori: "ungkapan" },
  { kata: "はい、元気です", arti: "ya, saya baik-baik", romaji: "hai, genki desu", kategori: "ungkapan" },
  { kata: "いいえ、元気じゃありません", arti: "tidak, saya tidak baik-baik", romaji: "iie, genki ja arimasen", kategori: "ungkapan" },
  { kata: "どうぞ", arti: "silakan", romaji: "douzo", kategori: "ungkapan" },
  { kata: "どうも", arti: "terima kasih (casual)", romaji: "doumo", kategori: "ungkapan" },
  { kata: "お邪魔します", arti: "permisi masuk", romaji: "ojamashimasu", kategori: "ungkapan" },
  { kata: "お邪魔しました", arti: "terima kasih atas keramahtamahan", romaji: "ojamashimashita", kategori: "ungkapan" },
  { kata: "頂きます", arti: "terima kasih (atas makanan)", romaji: "itadakimasu", kategori: "ungkapan" },
  { kata: "ご馳走様でした", arti: "terima kasih atas makanan", romaji: "gochisousama deshita", kategori: "ungkapan" },
  { kata: "お先に失礼します", arti: "permisi duluan", romaji: "osaki ni shitsurei shimasu", kategori: "ungkapan" },
  { kata: "お疲れ様です", arti: "selamat bekerja (saat pulang)", romaji: "otsukaresama desu", kategori: "ungkapan" },
  { kata: "頑張ってください", arti: "semangat!", romaji: "ganbatte kudasai", kategori: "ungkapan" },
  { kata: "頑張ります", arti: "saya akan berusaha", romaji: "ganbarimasu", kategori: "ungkapan" },
  { kata: "おめでとう", arti: "selamat", romaji: "omedetou", kategori: "ungkapan" },
  { kata: "お誕生日おめでとうございます", arti: "selamat ulang tahun", romaji: "otanjoubi omedetou gozaimasu", kategori: "ungkapan" },
  { kata: "明けましておめでとうございます", arti: "selamat tahun baru", romaji: "akemashite omedetou gozaimasu", kategori: "ungkapan" },
  { kata: "良いお年を", arti: "semoga tahun baru baik", romaji: "yoi otoshi wo", kategori: "ungkapan" },
  { kata: "今年もよろしくお願いします", arti: "tahun ini juga mohon bantuannya", romaji: "kotoshi mo yoroshiku onegaishimasu", kategori: "ungkapan" },
  { kata: "お久しぶり", arti: "lama tidak berjumpa", romaji: "ohisashiburi", kategori: "ungkapan" },
  { kata: "ご無沙汰しております", arti: "sudah lama tidak berhubungan", romaji: "gobusata shite orimasu", kategori: "ungkapan" },
  { kata: "お元気で", arti: "jaga kesehatan", romaji: "ogenkide", kategori: "ungkapan" },
  { kata: "さようなら", arti: "selamat tinggal", romaji: "sayounara", kategori: "ungkapan" },
  { kata: "また明日", arti: "sampai jumpa besok", romaji: "mata ashita", kategori: "ungkapan" },
  { kata: "また来週", arti: "sampai jumpa minggu depan", romaji: "mata raishuu", kategori: "ungkapan" },
  { kata: "また後で", arti: "sampai jumpa nanti", romaji: "mata atode", kategori: "ungkapan" },
  { kata: "では、また", arti: "sampai jumpa", romaji: "dewa, mata", kategori: "ungkapan" },
  { kata: "じゃあ、また", arti: "sampai jumpa (casual)", romaji: "jaa, mata", kategori: "ungkapan" },
  { kata: "バイバイ", arti: "bye-bye", romaji: "baibai", kategori: "ungkapan" },
  { kata: "またね", arti: "sampai jumpa (friendly)", romaji: "matane", kategori: "ungkapan" },
  { kata: "お大事に", arti: "jaga diri", romaji: "odaijini", kategori: "ungkapan" },
  { kata: "お体に気をつけて", arti: "hati-hati dengan kesehatan", romaji: "okarada ni ki wo tsukete", kategori: "ungkapan" },
  { kata: "いってらっしゃい", arti: "hati-hati di jalan", romaji: "itterasshai", kategori: "ungkapan" },
  { kata: "いってきます", arti: "saya pergi", romaji: "ittekimasu", kategori: "ungkapan" },
  { kata: "ただいま", arti: "saya pulang", romaji: "tadaima", kategori: "ungkapan" },
  { kata: "おかえりなさい", arti: "selamat datang kembali", romaji: "okaerinasai", kategori: "ungkapan" },
  { kata: "おやすみなさい", arti: "selamat tidur", romaji: "oyasuminasai", kategori: "ungkapan" },
  { kata: "おはよう", arti: "selamat pagi (casual)", romaji: "ohayou", kategori: "ungkapan" },
  { kata: "こんにちは", arti: "selamat siang", romaji: "konnichiwa", kategori: "ungkapan" },
  { kata: "こんばんは", arti: "selamat malam", romaji: "konbanwa", kategori: "ungkapan" },
  { kata: "おはようございます", arti: "selamat pagi (formal)", romaji: "ohayou gozaimasu", kategori: "ungkapan" },
  { kata: "こんにちは", arti: "selamat siang (formal)", romaji: "konnichiwa", kategori: "ungkapan" },
  { kata: "こんばんは", arti: "selamat malam (formal)", romaji: "konbanwa", kategori: "ungkapan" },
]